export default {
  lets_get_started: "let's get started",
  language_select_body_1: "what language do you want the app to be in?",
  language_select_body_2: "which currency do you want the app to show?",
  welcomeToRelai: "welcome to Relai",
  sosimple: "so simple",
  agreeRelai: "I agree to the Relai",
  agreeBity: "I agree to the Bity",
  termsandconditions: "terms and conditions",
  privacypolicy: "privacy policy",
  and: "and",
  startnow: "start now",
  restore_account: "restore account",
  noinvestmentyet: "no investment yet",
  buybtc: "buy",
  sellbtc: "sell",
  tapbuybtcbutton: "tap the Buy BTC button",
  tostartinvesting: "to start investing",
  sendbtc: "send",
  receivebtc: "receive",
  balance: "balance",
  unconfirmed: "unconfirmed",
  taptheimage: "tap the image",
  tobuyfirstbitcoin: "to buy your first Bitcoin",
  error_creating_order:
    "error while creating your investment, please try again later",
  settings: "settings",
  profile: "profile",
  rateus: "rate us",
  followus: "follow us",
  askforhelp: "contact us",
  security: "security",
  backupbtcwallet: "back-up BTC wallet",
  general: "general",
  changelanguage: "change language",
  legal: "legal",
  close: "close",
  reachouttous: "contact us",
  btcbackup: "wallet backup",
  first_purchase: "you’ve made your first purchase with Relai",
  btcaddress: "BTC address",
  copyaddress: "copy address",
  dismiss: "dismiss",
  addresscopied: "BTC address copied to clipboard",
  recipientbtcaddress: "recipient BTC address",
  entercorrectaddress: "please enter a correct BTC address",
  next: "next",
  back: "back",
  sendingbitcoin: "sending Bitcoin",
  half: "half",
  cancel: "cancel",
  addsomebtc: "add some BTC",
  maxbtcexceeded: "max BTC exceeded",
  youaresending: "you are sending",
  to: "to",
  confirm: "confirm",
  amount: "amount",
  date: "date",
  confirmations: "confirmations",
  blockheight: "block height",
  details: "details",
  whichiban: "from which IBAN will you be investing?",
  pay_with_yapeal: "pay with yapeal",
  entercorrectiban: "please enter a correct IBAN",
  creatingorder: "we are creating your investment",
  signingorder: "Signing your order",
  savingorder: "Saving order",
  retrievedetails: "Extracting order details",
  iwanttobuy: "I want to buy BTC",
  iwanttosell: "I want to sell BTC",
  buy: "buy",
  minpurchase: "minimum amount: {{min}} {{currency}}",
  sell: "sell",
  once: "once",
  weekly: "weekly",
  monthly: "monthly",
  dontforgetref: "don't forget the payment message",
  usefollowingref:
    "use the following payment message when making the order \n\n",
  tobankaccount: "to the following bank account",
  pay: "pay",
  fromyouraccount: "the payment has to come from your own bank account",
  tapholdcopy: "tap and hold any text to copy",
  recipient: "recipient",
  reference: "payment message",
  makesureuseref: "make sure to use the payment message indicated above",
  mighttake3days: "it might take up to 3 days to receive your Bitcoin",
  done: "done",
  illpaylater: "I'll pay later",
  youriban: "your IBAN",
  inforequired:
    "your IBAN, name and address information is required for the bank transfer",
  somethingwrong: "something went wrong, please try again later",
  entervalidiban: "please enter a valid IBAN",
  paymentdetails: "payment details",
  amountsentto: "the amount will be sent to",
  personalinfo: "personal information",
  fullname: "Full name",
  address: "address",
  // provideaddress: 'provide your full name',
  txoverview: "transaction overview",
  youareselling: "you are selling",
  inexchangeto: "in exchange to",
  congrats: "congratulations!",
  investmentonitsway: "your investment is on its way",
  sold: "sold",
  received: "received",
  status: "status",
  pending: "awaiting your payment",
  refno: "payment message",
  orderid: "order ID",
  maxpurchase: "max amount: {{max}} {{currency}}",
  keepappsecure: "to keep your Relai app secure",
  choosepin: "choose a PIN code",
  confirmpin: "confirm your PIN code",
  entriesnotmatch: "your entries did not match",
  tryagain: "please try again",
  enterpin: "enter your PIN code",
  incorrectpin: "incorrect PIN code",
  alwayspin: "enable passcode",
  restore_btc: "enter your 12 backup seed words",
  typo_error: "One of your words has a typo",
  restorebtcwarning:
    "we will only check locally that your investment BTC wallet address matches",
  agreetoterms:
    "you need to agree to the Relai and Bity terms & conditions and privacy policy",
  restoringaccount: "restoring Relai account",
  noaccountfound:
    "we couldn't find your account, please verify your information and try again",
  provideibanwallet: "please provide a correct IBAN and seed",
  maxattempts: "maximum attempts reached",
  protectinfo:
    "to protect your information, access to Relai has been locked for 5 minutes",
  cancelorder: "cancel order",
  cancellingorder:
    "you are about to cancel your order \n\n make sure to stop your payment if this is a recurring order",
  keeporder: "keep order",
  cancellingerror:
    "we are not able to cancel your order at the moment. please try again later",
  investedsofar: "invested so far",
  succeeded: "succeeded",
  onlyhavetofillonce: "you only have to fill this in once",
  invested: "invested",
  changecurrency: "change default currency",
  payto: "payment details",
  taptochange: "tap to change",
  delete: "delete",
  toreceive: "estimated",
  fees: "our fees",
  totalfee: "total fees",
  relaifee: "Relai service fee",
  bityfee: "Bity broker fee",
  onitsway: "BTC on its way",
  copyall: "copy all",
  payin48hours:
    "to ensure the correct processing of your payment please pay within 48 hours",
  firstordertoohigh: "Your first order should be <{{max}} {{currency}}",
  fast: "fast",
  slow: "slow",
  medium: "medium",

  // v1.3
  referralcode: "do you have a referral code?",
  codenotexisting: "The referral code you entered doesn't exist",
  provideaddress: "Provide your address",
  providefullname: "Provide your full name",
  zip: "Zip",
  providezip: "Provide your ZIP code",
  city: "City",
  providecity: "Provide your City",
  country: "Country",
  providecountry: "Select your Country",
  providereferralcode: "Provide your referral code",
  welcomereferral: "Welcome to Relai Referral Program!",
  sharecode: "Share your Referral Code with other people",
  sharecode2:
    "They will pay 0.5% less in Transaction Fees (2.5% instead of 3%)",
  sharecode3chf:
    "You will earn 0.5% on all their Investments (e.g. 5 CHF per 1'000 CHF invested)",
  sharecode3eur:
    "You will earn 0.5% on all their Investments (e.g. 5 EUR per 1'000 EUR invested)",
  sharecode4:
    "You will receive your rewards to your BTC wallet every 15th of the month if you accumulated more than 10",
  totalearnings: "Current earnings",
  noreferralearnings: "No referral earnings",
  startsharingcode: "Start sharing your code",
  toearnbtc: "to earn BTC from your referral code",
  generatecode: 'Generate your Referral Code by clicking "activate"',
  hitherecode: "Hi there,\nHere is my Relai referral code: ",
  hitherecode2:
    "😎\nIf you use it for investing in Bitcoin with the Relai App, you pay 0.5% less in fees! 👍\nRelai is the world’s easiest way to invest in Bitcoin - made in Switzerland!🇨🇭\niOS: https://apps.apple.com/app/id1513185997\nAndroid: https://play.google.com/store/apps/details?id=com.relai",
  shareyourcode: "Share your Relai code",
  refcode: "Referral code:",
  paymentinformation: "Payment Information",
  share: "share",
  pleasebackup: "please backup your wallet",
  pending2: "Pending",
  transactions: "Transactions",
  awaitingpayment: "awaiting payment",
  orderdetails: "Order Details",
  purchased: "Purchased",
  purchasepending: "Purchase Pending",
  sent: "Sent",
  rewardearned: "Reward Earned",
  rewardwithdrawn: "Reward Paid Out",
  currency: "Currency",
  yourpassphrase: "your passphrase",
  passphrasesaved: "I wrote down my seed",
  willdolater: "I will do it later",
  checkwords:
    "type in the seed phrase you just wrote down to check the validity of the backup",
  goodtry: "Good try",
  cannotuseowncode: "You cannot use your own referral code",
  edit: "Edit",
  continue: "Continue anyway",
  addressbig: "Address",
  activate: "Activate",
  sharecodebutton: "Share code",
  asell: "Sell",
  // v1.3.2
  archived: "Archived",
  fee: "fee",
  oneh: "1 hour",
  halfh: "30 min",
  oneblock: "10 min",
  notenougfund: "Not enough BTC, try sending a smaller amount!",
  provideswift: "Provide your BIC/SWIFT",
  swift: "BIC/SWIFT",
  copied: "copied",
  sellsuccess: "your money is on its way",
  economy: "minimum",
  quotaError:
    "you have reached your daily limit, please cancel some open orders or wait 24 hours",
  minsell: "minimum amount: 0.0002 BTC",
  showcancelledtransactions: "show cancelled transactions",
  exchangerate: "exchange rate",
  insufficientfunds: "Insufficient funds, please try with lower fees",
  // v1.4
  btc_wallet_qr_code: "BTC Wallet QR Code",
  scanpaperwallet: "scan paper wallet",
  custom: "custom",
  feetoolow: "sending might not work if fees are too low",
  stackedalot: "you've stacked quite a lot!",
  considerbitbox:
    "consider upgrading your security with a hardware wallet. we recommend the BitBox02",
  usecoderelai: " (use code RELAI21) ",
  whyhardwarewallet: "why hardware wallets?",
  whyhardwarewalletans:
    "A hardware wallet is a device specifically made for securely storing your bitcoin. Your funds are pretty safe on your phone, but the chance that your phone gets hacked, stolen or infected with malware is much higher than for a specialized hardware device.\n \n If you have more than €500 in bitcoin, we recommend investing some money in improving your security.",
  checkitout: "check it out",
  maybelater: "maybe later",
  why: "why ?",
  letsgo: "let's go!",
  restoreexistingbackup: "restore existing backup",
  onboarding_subtitle: "the easiest way to save bitcoin",
  onboarding_list_item_1: "no account or identity registration",
  onboarding_list_item_2: "automate your recurring purchases",
  onboarding_list_item_3: "minimum investment starting at 10 EURO/CHF",
  onboarding_list_item_4: "you always control your bitcoin",
  onboarding_step_title: "how it works",
  onboarding_step_index: "step {{index}} / 3",
  onboarding_step_1: "you create your order on the app",
  onboarding_step_2: "you send us a bank transfer",
  onboarding_step_3: "we send bitcoin to your wallet",
  start: "start",
  restore_account_subtitle: "we’ll restore your account\nin two easy steps",
  restore_account_step_1_description: "please enter an IBAN you used on Relai",
  restore_account_step_2_description: "enter your 12 backup seed words",
  creatingbitcoinwallet: "creating Bitcoin wallet",
  exceeds_quota:
    "you have reached your daily limit, please cancel some open orders or wait 24 hours",
  invalid_bank_account: "invalid bank account, please provide a valid IBAN/BIC",
  invalid_country_code: "your country code is invalid",
  invalid_crypto_address: "your BTC wallet address is invalid",
  invalid_bank_account_owner_address:
    "your home address is invalid, please provide a valid address",
  malformed_request:
    "something went wrong, please try again later or get in touch with our support team via support@relai.ch",
  revolutiban:
    "this is the Revolut collective account's IBAN and cannot be used",
  enablebiometrics: "enable Touch ID / Face ID",
  noutxo:
    "an error happened when preparing your transaction [1], please try again later or get in touch with our support team via support@relai.ch",
  noutxo2:
    "an error happened when preparing your transaction [2], please try again later or get in touch with our support team via support@relai.ch",
  noinout:
    "an error happened when preparing your transaction [3], please try again later or get in touch with our support team via support@relai.ch",
  noinput:
    "an error happened when preparing your transaction [4], please try again later or get in touch with our support team via support@relai.ch",
  changeerror:
    "an error happened when preparing your transaction [5], please try again later or get in touch with our support team via support@relai.ch",
  feetoohigh:
    "your transaction fees are higher than the amount, please try again with lower fee or slower speed",
  totalrecipienthigherthanbalance:
    "the total amount of your transaction exceeds your balance, please try sending a lower amount",
  notpkey: "make sure to scan a valid private key",
  emptywallet: "this wallet has no BTC in it",
  paperwalletfee: "this action will cost a small fee",
  countrynotsupported: "sorry we don't support your country yet",
  ordercreated:
    "we'll send you your bitcoin after you have made the bank transfer",
  amountdetected: "amount detected",
  containsamount: "this QR code also contains an amount",
  updateamount: "do you wish to update your transaction with that amount?",
  fixedfee: "fixed fee",
  additionalinformation: "Additional Information",
  buyword: "buy",
  errorbroadcasting:
    "Unable to broadcast your transaction, please try again later",

  // report generation
  noorders: "no orders",
  noordersdescp: "There are currently no orders associated with this account",
  nocompleteorders: "no complete orders",
  nocompleteordersdescp:
    "There are currently no complete orders associated with this account within the specified period",
  generatereport: "Generate Report",
  generatereportdescp:
    "you can generate and download your account statement for tax or administration purposes",
  from: "from",
  generatingreport: "generating your report",
  generate: "Generate",
  advancedoptions: "advanced options",
  accountstatement: "account statement",
  invalidperiod: "invalid period",
  selectvalidtimeperiod: "please select a valid time period",
  congratulations: "congratulations",
  congratulations_body_1:
    "let’s make sure you won’t lose it by backing up your bitcoin wallet",
  congratulations_body_2: "this will only take a few minutes",

  //backup
  check_the_backup: "check the backup",
  backup_step1:
    "your relai wallet is represented by a secure, unique 12-word phrase",
  backup_step2: "write down these 12 words and store them safely",
  savedmnemonic: "I saved my 12 words (seed)",
  backup_list_item_1:
    "anyone with access to the phrase can access your bitcoin",
  backup_list_item_2: "do not share it with anyone",
  backup_list_item_3: "do not store the phrase digitally",
  backup_list_item_4: "we cannot help you recover your phrase if you lose it",
  backup_list_item_5:
    "as long as you have the phrase, you can always restore your wallet",
  backup_popup_title: "that was quick... 😏",
  backup_popup_message_1: "seriously though, this is important",
  backup_popup_message_2:
    "please read those 5 points carefully before continuing",
  okay: "okay",
  check_my_backup: "check my backup",
  skip_backup_warning: "skip, I know what I'm doing",

  //internet
  nointernet: "oh no! Looks like we've lost connection 😔",
  internet_back: "and we're back! 👌🏽 We thought we lost you for a sec 😉",

  //external_wallet
  buy_to_external_wallet: "buy to external wallet",
  stack_external_wallet_alert_1:
    "you can use Relai to directly stack to your existing external wallet",
  stack_external_wallet_alert_2:
    "during purchase, you'll need to manually sign a message to verify the wallet",
  nevermind: "nevermind",
  signature: "signature",
  message: "message",
  sign_message_title: "now it's time to sign your message",
  message_description:
    "learn how to sign a message by visiting our support section on relai.ch",
  paste_signature: "paste your signature here:",
  enter_signature: "please enter your signature",
  external: "external",
  ext_addr: "external address",

  //backup-2
  backup_success_popup_title: "you're all backed up 🥇",
  backup_success_popup_message_1:
    "nice job. It looks like you've written your 12 words somewhere safe",
  start_buying: "start buying",

  //errors
  something_went_wrong:
    "We're sorry, something has gone wrong. Please try later",
  error_saving_order:
    "error while saving your investment, please try again later",
};
