export default {
  welcomeToRelai: 'bienvenido a Relai',
  sosimple: 'tan simple',
  agreeRelai: 'Estoy de acuerdo con el Relai',
  agreeBity: 'Estoy de acuerdo con el Bity',
  termsandconditions: 'términos y condiciones',
  privacypolicy: 'política de privacidad',
  and: 'y',
  startnow: 'empezar ahora',
  restore_account: 'restaurar cuenta',
  noinvestmentyet: 'no hay inversión todavía',
  buybtc: 'comprar',
  sellbtc: 'vender',
  tapbuybtcbutton: 'tocar el botón de comprar BTC',
  tostartinvesting: 'empezar a invertir',
  sendbtc: 'enviar',
  receivebtc: 'recibir',
  balance: 'balance',
  unconfirmed: 'no confirmado',
  taptheimage: 'tocar la imagen',
  tobuyfirstbitcoin: 'para comprar su primer Bitcoin',
  errorCreatingOrder:
    'error al crear su inversión, por favor inténtelo más tarde',
  settings: 'ajustes',
  profile: 'perfil',
  rateus: 'califícanos',
  followus: 'síguenos',
  askforhelp: 'contacta con nosotros',
  security: 'seguridad',
  backupbtcwallet: 'copia de seguridad de la cartera BTC',
  general: 'general',
  changelanguage: 'cambiar idioma',
  legal: 'legal',
  close: 'cerrar',
  followusonsocialmedia: 'síguenos',
  reachouttous: 'contacta con nosotros',
  btcbackup: 'Copia de seguridad de BTC',
  backuptextpre: 'asegúrate de anotar las siguientes',
  twelvewords: '12 palabras',
  backuptextpost:
    '(semilla) y manténgalas seguras para que pueda restaurar su BTC cuando pierda su teléfono',
  savedmnemonic: 'Guardé mis 12 palabras (semilla)',
  btcaddress: 'Dirección de BTC',
  copyaddress: 'copiar dirección',
  dismiss: 'descartar',
  addresscopied: 'Dirección BTC copiada al portapapeles',
  recipientbtcaddress: 'dirección BTC del destinatario',
  entercorrectaddress: 'por favor, introduzca una dirección BTC correcta',
  next: 'siguiente',
  back: 'back',
  sendingbitcoin: 'enviando Bitcoin',
  half: 'mitad',
  cancel: 'cancelar',
  addsomebtc: 'añadir algunos BTC',
  maxbtcexceeded: 'máximo BTC superado',
  youaresending: 'estás enviando',
  to: 'a',
  confirm: 'confirmar',
  amount: 'importe',
  date: 'fecha',
  confirmations: 'confirmaciones',
  blockheight: 'altura del bloque',
  details: 'detalles',
  whichiban: '¿de qué IBAN va a invertir?',
  entercorrectiban: 'por favor, introduzca un IBAN correcto',
  creatingorder: 'estamos creando su inversión',
  iwanttobuy: 'Quiero comprar BTC',
  iwanttosell: 'Quiero vender BTC',
  buy: 'comprar',
  minpurchase: 'cantidad mínima: {{min}} {{currency}}',
  sell: 'vender',
  once: 'una vez',
  weekly: 'semanal',
  monthly: 'mensual',
  dontforgetref: "no olvidar el mensaje de pago",
  usefollowingref:
    'utilice el siguiente mensaje de pago al hacer el pedido \n\n',
  tobankaccount: 'a la siguiente cuenta bancaria',
  pay: 'pagar',
  fromyouaccount: 'el pago debe proceder de su propia cuenta bancaria',
  tapholdcopy: 'pulse y mantenga pulsado cualquier texto para copiarlo',
  recipient: 'destinatario',
  reference: 'mensaje de pago',
  makesureuseref: 'asegúrese de utilizar el mensaje de pago indicado anteriormente',
  mighttake3days: 'puede tardar hasta 3 días en recibir su Bitcoin',
  done: 'hecho',
  illpaylater: "'Pagaré más tarde',
  youriban: 'su IBAN',
  inforequired:
    'su IBAN, nombre y dirección son necesarios para la transferencia bancaria',
  somethingwrong: 'algo ha ido mal, por favor inténtelo más tarde',
  entervalidiban: 'por favor, introduzca un IBAN válido',
  paymentdetails: 'detalles del pago',
  amountsentto: 'el importe se enviará a',
  personalinfo: 'información personal',
  fullname: 'Nombre completo',
  address: 'dirección',
  // provideaddress: 'proporcione su nombre completo',
  txoverview: 'resumen de la transacción',
  youareselling: 'estás vendiendo',
  inexchangeto: 'a cambio de',
  congrats: '¡felicidades!
  investmentonitsway: 'su inversión está en camino',
  sold: 'vendido',
  received: 'recibido',
  status: 'estado',
  pending: 'a la espera de su pago',
  refno: 'mensaje de pago',
  orderid: 'ID del pedido',
  maxpurchase: 'importe máximo: {{max}} {{currency}}',
  keepappsecure: 'para mantener la seguridad de tu aplicación Relai',
  choosepin: 'elija un código PIN',
  confirmpin: 'confirma tu código PIN',
  entriesnotmatch: 'tu PIN no coincide',
  tryagain: 'por favor, inténtalo de nuevo',
  enterpin: 'introduzca su código PIN',
  incorrectpin: 'código PIN incorrecto',
  alwayspin: 'habilitar código de acceso',
  restore_btc: 'introduzca sus 12 palabras clave de respaldo',
  typo_error: 'Una de tus palabras tiene un error tipográfico',
  restorebtcwarning:
    'sólo comprobaremos localmente que la dirección de su monedero BTC de inversión coincide',
  agreetoterms:
    'tienes que aceptar los términos y condiciones de Relai y Bity y la política de privacidad',
  restoringaccount: 'restaurar la cuenta de Relai',
  noaccountfound:
    "no hemos podido encontrar tu cuenta, por favor verifica tu información e inténtalo de nuevo",
  provideibanwallet: 'por favor, proporcione un IBAN y una semilla correctos',
  maxattempts: 'se ha alcanzado el máximo de intentos',
  protectinfo:
    'para proteger su información, el acceso a Relai ha sido bloqueado durante 5 minutos',
  cancelorder: 'cancelar pedido',
  cancellingorder:
    'está a punto de cancelar su pedido \n\n asegúrese de detener su pago si se trata de un pedido recurrente',
  keeporder: 'mantener pedido',
  cancellingerror:
    'no podemos cancelar su pedido en este momento. por favor, inténtelo más tarde',
  investedsofar: 'invertido hasta el momento',
  succeeded: 'realizado con éxito',
  onlyhavetofillonce: 'sólo tiene que rellenar esto una vez',
  invested: 'invertido',
  changecurrency: 'cambiar la moneda por defecto',
  payto: 'datos de pago',
  taptochange: 'toque para cambiar',
  delete: 'eliminar',
  toreceive: 'estimado',
  fees: 'nuestras comisiones',
  totalfee: 'comisiones totales',
  relaifee: 'Comisión de servicio de Relai',
  bityfee: 'Comisión de intermediación de Bity',
  onitsway: 'BTC en camino',
  copyall: 'Copia todo',
  payin48hours:
    'para asegurar el correcto procesamiento de su pago por favor pague dentro de las 48 horas',
  firstordertoohigh: 'Su primer pedido debe ser <{{max}} {{currency}}',
  fast: 'rápido',
  lento: 'lento',
  medium: 'medio',

  // v1.3
  referralcode: '¿tiene un código de referido?
  codenotexisting: "El código de referido que has introducido no existe",
  provideaddress: 'Proporcione su dirección',
  providefullname: 'Proporcione su nombre completo',
  zip: 'Código postal',
  providezip: 'Proporcione su código postal',
  city: 'Ciudad',
  providecity: 'Proporcione su ciudad',
  country: 'País',
  providecountry: 'Seleccione su País',
  providereferralcode: 'Proporcione su código de referido',
  welcomereferral: '¡Bienvenido al programa de referidos de Relai!
  sharecode: 'Comparte tu código de referido con otras personas',
  sharecode2:
    'Pagarán un 0,5% menos en las Comisiones de Transacción (2,5% en lugar de 3%)',
  sharecode3chf:
    "Ganarás un 0,5% sobre todas sus inversiones (por ejemplo, 5 CHF por cada 1'000 CHF invertidos)",
  sharecode3eur:
    "Ganarás el 0,5% sobre todas sus inversiones (por ejemplo, 5 EUR por cada 1.000 EUR invertidos)",
  sharecode4:
    'Recibirás tus recompensas en tu cartera de BTC cada 15 de mes si has acumulado más de 10',
  totalearnings: 'Ganancias totales',
  noreferralearnings: 'No hay ganancias por referidos',
  startsharingcode: 'Empieza a compartir tu código',
  toearnbtc: 'Ganar BTC con tu código de referido',
  generatecode: 'Genera tu código de referido haciendo clic en "activar"',
  hitherecode: 'Hola,\nAquí está mi código de referido Relai: ',
  hitherecode2:
    '😎\nSi lo usas para invertir en Bitcoin con la App Relai, ¡pagas un 0,5% menos de comisiones! 👍\nRelai es la forma más fácil del mundo de invertir en Bitcoin - ¡hecho en Suiza!🇨🇭\niOS: https://apps.apple.com/app/id1513185997\nAndroid: https://play.google.com/store/apps/details?id=com.relai',
  shareyourcode: 'Comparte tu código Relai',
  refcode: 'Código de referido:',
  paymentinformation: 'Información de pago',
  share: 'compartir',
  pleasebackup: 'Por favor, haga una copia de seguridad de su cartera',
  pending2: 'Pendiente',
  transactions: 'Transacciones',
  awaitingpayment: 'en espera de pago',
  orderdetails: 'Detalles del pedido',
  purchased: 'Comprado',
  purchasepending: 'Compra pendiente',
  sent: 'Enviado',
  rewardearned: 'Recompensa ganada',
  rewardwithdrawn: 'Recompensa pagada',
  currency: 'Moneda',
  yourpassphrase: 'su semillas mnemotécnicas',
  nevershareseed: '* ¡Nunca compartas tu semillas mnemotécnicas con nadie!
  passphrasesaved: 'He guardado mi semillas mnemotécnicas',
  willdolater: 'Lo haré más tarde',
  checkwords:
    'Para asegurarte de que has escrito la semillas mnemotécnicas, proporciona las palabras',
  goodtry: 'Buen intento',
  cannotuseowncode: 'No puedes usar tu propio código de referido',
  edit: 'Editar',
  continue: 'Continuar de todos modos',
  addressbig: 'Dirección',
  activate: 'Activar',
  sharecodebutton: 'Compartir código',
  asell: 'Vender',
  // v1.3.2
  archived: 'Archivado',
  fee: 'comisión',
  oneh: '1 hora',
  halfh: '30 min',
  oneblock: '10 min',
  notenougfund: 'No hay suficientes BTC, intente enviar una cantidad menor',
  provideswift: 'Proporcione su BIC/SWIFT',
  swift: 'BIC/SWIFT',
  copied: 'copiado',
  sellsuccess: 'su dinero está en camino',
  economy: 'economía',
  quotaError:
    'Ha alcanzado su límite diario, por favor cancele algunas órdenes abiertas o espere 24 horas',
  minsell: 'cantidad mínima: 0.001 BTC',
  showcancelledtransactions: 'mostrar transacciones canceladas',
  exchangerate: 'tipo de cambio',
  insufficientfunds: 'Fondos insuficientes, por favor inténtelo con tarifas más bajas',
  // v1.4
  scanpaperwallet: 'escanear cartera de papel',
  custom: 'custom',
  feetoolow: 'el envío podría no funcionar si las tarifas son demasiado bajas',
  stackedalot: "¡has apilado bastante!",
  considerbitbox:
    'considera mejorar tu seguridad con un monedero hardware. recomendamos el BitBox02:'
  whyhardwarewallet: '¿por qué una cartera de hardware?',
  whyhardwarewalletans:
    'Un monedero de hardware es un dispositivo hecho específicamente para almacenar de forma segura tu bitcoin. Tus fondos están bastante seguros en tu teléfono, pero la posibilidad de que tu teléfono sea hackeado, robado o infectado con malware es mucho mayor que para un dispositivo de hardware especializado.\n \n Si tienes más de 500€ en bitcoin, te recomendamos que inviertas algo de dinero en mejorar tu seguridad.'
  checkitout: 'compruébalo',
  maybelater: 'tal vez más tarde',
  why: '¿por qué?
  letsgo: "¡vamos!",
  restoreexistingbackup: 'restaurar la copia de seguridad existente',
  onboarding_subtitle: 'la forma más fácil de guardar bitcoin',
  onboarding_list_item_1: 'sin registro de cuenta o identidad',
  onboarding_list_item_2: 'automatizar sus compras recurrentes',
  onboarding_list_item_3: "inversión mínima a partir de 10 EURO/CHF",
  onboarding_list_item_4: 'usted siempre controla su bitcoin',
  onboarding_step_title: 'cómo funciona',
  onboarding_step_index: 'paso {{index}} / 3',
  onboarding_step_1: 'creas tu pedido en la app',
  onboarding_step_2: 'nos envías una transferencia bancaria',
  onboarding_step_3: 'te enviamos bitcoin a tu cartera',
  start: 'inicio',
  restore_account_subtitle: 'restauramos tu cuenta\nen dos sencillos pasos',
  restore_account_step_1_description: 'por favor, introduce un IBAN que hayas utilizado en Relai',
  restore_account_step_2_description: 'introduzca sus 12 palabras clave de respaldo',
  creatingbitcoinwallet: 'crear cartera Bitcoin',
  exceeds_quota:
    'Ha alcanzado su límite diario, por favor cancele algunas órdenes abiertas o espere 24 horas',
  invalid_bank_account: 'Cuenta bancaria inválida, por favor proporcione un IBAN válido',
  invalid_country_code: 'Su código de país no es válido',
  invalid_crypto_address: 'La dirección de tu monedero BTC no es válida',
  invalid_bank_account_owner_address:
    'La dirección de su casa no es válida, por favor proporcione una dirección válida',
  malformed_request:
    'algo ha ido mal, por favor inténtalo de nuevo más tarde o ponte en contacto con nuestro equipo de soporte',
};
