export default {
  welcomeToRelai: 'Tervetuoloa Relaihin',
  sosimple: 'niin helppoa',
  onboarding1_1: 'helpoin tapa',
  onboarding1_2: 'sijoittaa bitcoiniin',
  onboarding2_1: 'ei tiliä',
  onboarding2_2: 'ei rekisteröitymistä',
  onboarding2_3: 'ei talletusta',
  autoinvest: 'sijoita automaattisesti',
  onboarding3_1: 'automatisoi toistuvat',
  onboarding3_2: 'sijoitukset alkaen 10 CHF',
  agreeRelai: 'hyväksyn Relai:n',
  agreeBity: 'hyväksyn Bity:n',
  termsandconditions: 'käyttöehdot',
  privacypolicy: 'tietosuojakäytäntö',
  and: 'ja',
  startnow: 'aloita nyt',
  restoreaccount: 'palauta tili',
  creatingbitcoinwallet: 'luodaan bitcoin-lompakkoa',
  noinvestmentyet: 'ei sijoituksia vielä',
  buybtc: 'osta',
  sellbtc: 'myy',
  tapbuybtcbutton: 'napsauta osta BTC-nappia',
  tostartinvesting: 'aloittaaksesi sijoittamisen',
  sendbtc: 'lähetä',
  receivebtc: 'vastaanota',
  balance: 'saldo',
  unconfirmed: 'vahvistamaton',
  taptheimage: 'napsauta kuvaa',
  tobuyfirstbitcoin: 'ostaaksesi ensimmäisen bitcoinisi',
  errorCreatingOrder:
    'tapahtui virhe luodessamme sijoitustasi, ole hyvä ja yritä hetken kuluttua uudestaan',
  settings: 'asetukset',
  profile: 'profiili',
  rateus: 'arvostele sovellus',
  followus: 'seuraa meitä',
  askforhelp: 'pyydä apua',
  security: 'turvallisuus',
  backupbtcwallet: 'varmuuskopioi BTC-lompakko',
  general: 'yleinen',
  changelanguage: 'vaihda kieli',
  legal: 'oikeudelliset tiedot',
  close: 'sulje',
  followusonsocialmedia: 'seuraa meitä sosiaalisessa mediassa',
  reachouttous: 'ota yheyttä',
  btcbackup: 'BTC-varmuuskopio',
  backuptextpre: 'varmista, että olet kirjoittanut ylös seuraavat',
  twelvewords: '12 sanaa',
  backuptextpost:
    '(seed) ja pidä niistä huoli, jotta voit palauttaa BTC-lompakkosi jos puhelimesi katoaa',
  savedmnemonic: 'olen tallentanut minun 12 sanaa (seed)',
  btcaddress: 'BTC osoite',
  copyaddress: 'kopioi BTC osoite',
  dismiss: 'ohita',
  addresscopied: 'BTC osoite kopioitu leikepöydälle',
  recipientbtcaddress: 'vastaanottajan  BTC osoite',
  entercorrectaddress: 'ole hyvä ja syötä oikea BTC osoite',
  next: 'seuraava',
  back: 'takaisin',
  sendingbitcoin: 'olet lähettämässä bitcoinia',
  half: 'puoli',
  cancel: 'peruuta',
  addsomebtc: 'lisää  BTC:tä',
  maxbtcexceeded: 'maksimi BTC määrä ylittynyt',
  youaresending: 'olet lähettämässä',
  to: 'osoitteeseen',
  confirm: 'vahvista',
  amount: 'määrä',
  date: 'päivämäärä',
  confirmations: 'vahvistuksia',
  blockheight: 'lohkonumero',
  details: 'lisätiedot',
  whichiban: 'mistä IBAN tilinumerosta tulet sijoittamaan?',
  entercorrectiban: 'ole hyvä ja syötä oikea IBAN tilinumero',
  creatingorder: 'olemme luomassa sijoitustasi',
  iwanttobuy: 'haluan ostaa BTC:tä',
  iwanttosell: 'haluan myydä BTC:tä',
  buy: 'osta',
  minpurchase: 'minimi määrä: {{min}} {{currency}}',
  sell: 'myy',
  once: 'kerran',
  weekly: 'viikoittain',
  monthly: 'kuukausittain',
  dontforgetref: "älä unohda tilisiirron viestiä",
  usefollowingref:
    'käytä oheista viestiä tehdessäsi tilisiirtoa \n\n',
  tobankaccount: 'oheiselle pankkitilille',
  pay: 'maksa',
  fromyouraccount: 'tilisiirron on tultava pankkitililtäsi',
  tapholdcopy: 'napsauta ja pidä pohjassa kopiodaksesi tekstiä',
  recipient: 'saaja',
  reference: 'tilisiirron viesti',
  makesureuseref: 'muista käyttää yllä olevaa viestiä tehdessäsi tilisiirtoa',
  mighttake3days: 'Bitcoinisi vastaanottaminem saattaa kestää jopa 3 päivää',
  done: 'valmis',
  illpaylater: "maksan myöhemmin",
  inforequired:
    'IBAN tilinumerosi, nimi sekä osoite vaaditaan tilisiirron tekemiseen',
  somethingwrong: 'jokin meni pieleen, ole hyvä ja yritä hetken kuluttua uudestaan',
  entervalidiban: 'ole hyvä ja syötä oikea IBAN tilinumero',
  paymentdetails: 'tilisiirron tiedot',
  amountsentto: 'summa siirretaan',
  personalinfo: 'henklökohtaiset tiedot',
  fullname: 'etu-ja sukunimi',
  address: 'osoite',
  // provideaddress: 'syötä etu-ja sukunimesi',
  txoverview: 'transaktion yleiskatsaus',
  youareselling: 'olet myymässä',
  inexchangeto: 'saat takaisin',
  congrats: 'onnittelut!',
  investmentonitsway: 'sijoituksesi on matkalla',
  sold: 'myyty',
  received: 'vastaanotettu',
  status: 'tila',
  pending: 'odottaa maksua',
  refno: 'maksun viesti',
  orderid: 'tilausnumero',
  maxpurchase: 'maksimi summa: {{max}} {{currency}}',
  keepappsecure: 'pitääksesi Relai-solvelluksesi turvassa',
  choosepin: 'valitse PIN koodi',
  confirmpin: 'vahvista PIN koodi',
  entriesnotmatch: 'syötteet eivät täsmää',
  tryagain: 'ole hyvä ja yritä uudestaan',
  enterpin: 'syötä PIN koodi',
  incorrectpin: 'väärä PIN koodi',
  alwayspin: 'ota käyttöön salasana',
  restoreiban: 'minkä IBAN tilinumeron kanssa käytit Relai-sovellusta',
  restorebtc: 'syötä 12 sanaasi (seed)',
  restorebtcwarning:
    'tarkistamme vain paikallisesti, että BTC-lompakkosi osoite täsmää',
  agreetoterms:
    'hyväksyt Relai:n seka Bity:n käyttöehdot ja tietosuojakäytännön',
  restoringaccount: 'Relai-tilin palauttaminen',
  noaccountfound:
    "emme löytäneet tiliäsi, ole hyvä ja varmista tietosi ja yritä uudestaan",
  provideibanwallet: 'ole hyvä ja syötä oikea IBAN tilinumero sekä 12 sanaa',
  maxattempts: 'suurin sallittu määrä yrityksiä ylitetty',
  protectinfo:
    'suojellaksemme tietojasi, Relai-sovellus on lukittu 5 minuutiksi',
  cancelorder: 'peruuta tilaus',
  cancellingorder:
    'olet peruuttamassa tilaustasi \n\n varmista, että lopetat tilisiirtosi jos tämä on toistuva maksu',
  keeporder: 'pidä tilaus ennalla',
  cancellingerror:
    'emme voi peruuttaa tilaustasi juuri nyt, ole hyvä ja yritä hetken kuluttua uudestaan',
  investedsofar: 'sijoitettu tähän mennessä',
  succeeded: 'onnistununt',
  onlyhavetofillonce: 'tämä pitää täyttää vain kerran',
  invested: 'sijoitettu',
  changecurrency: 'muuta oletusvaluuttaa',
  payto: 'maksun tiedot',
  taptochange: 'napsauta muuttaaksesi',
  delete: 'poista',
  toreceive: 'arvioitu',
  fees: 'palkkiomme',
  totalfee: 'kokonaispalkkiot',
  relaifee: 'Relai-palvelumaksu',
  bityfee: 'Bity-välityspalkkio',
  onitsway: 'BTC on matkalla',
  copyall: 'kopioi kaikki',
  payin48hours:
    'varmistaaksesi maksun onnistumisen, maksa 48 tunnin kuluessa',
  firstordertoohigh: 'Ensimmäisen tilauksesi on oltava <{{max}} {{currency}}',
  fast: 'nopea',
  slow: 'hidas',
  medium: 'mediumi',
  // v1.3
  referralcode: 'onko sinulla referoinitkoodia?',
  codenotexisting: "Syöttamäsi referointikoodi ei ole olemassa",
  provideaddress: 'Syötä osoitteesi',
  providefullname: 'Syötä etu-ja sukunimesi',
  zip: 'Zip-koodi',
  providezip: 'Syötä ZIP-koodi',
  city: 'Kaupunki',
  providecity: 'Syötä kaupunki',
  country: 'Maa',
  providecountry: 'Syötä maa',
  providereferralcode: 'Syötä referointikoodisi',
  welcomereferral: 'Tervetuloa Relai:n referointiohjelmaan!',
  sharecode: 'Jaa referoinitkoodisi muiden kanssa',
  sharecode2:
    'He maksavat 0,5% vähemmän transaktiopalkkioina (2,5% 3%:n sijaan)',
  sharecode3chf:
    "Ansaitset 0,5% kaikista heidän sijoituksistaan ​​(esim. 5 CHF kun sijoitettu 1 000 CHF)",
  sharecode3eur:
    "Ansaitset 0,5% kaikista heidän sijoituksistaan ​​(esim. 5 EUR kun sijoitettu 1 000 EUR)",
  sharecode4:
    'Saat palkkiot BTC-lompakkoon joka kuukauden 15. päivänä jos niitä on kertynyt yli 10',
  totalearnings: 'Kokonaistulot',
  noreferralearnings: 'Ei tuloja referoinnista',
  startsharingcode: 'Aloita koodisi jakaminen',
  toearnbtc: 'ansaitaksesi BTC:tä referointikoodistasi',
  generatecode: 'Luo referointikoodisi napsauttamalla "aktivoi"',
  hitherecode: 'Hei,\n tässä on Relai-referointikoodini: ',
  hitherecode2:
    '😎\nJos käytät sitä Bitcoiniin sijoittamiseen Relai-sovelluksessa, maksat 0,5% vähemmän palkkiota! 👍 \ nRelai on maailman helpoin tapa sijoittaa Bitcoiniin - valmistettu Sveitsissä! 🇨🇭 \ niOS: https://apps.apple.com/app/id1513185997\nAndroid: https://play.google.com/store/ sovellukset / tiedot? id = com.relai',
  shareyourcode: 'Jaa Relai-referointikoodisi',
  refcode: 'Referoinitkoodi:',
  paymentinformation: 'Maksun tiedot',
  share: 'jaa',
  pleasebackup: 'ole hyvä ja varmuuskopioi lompakkosi',
  pending2: 'Odottaa',
  transactions: 'Transaktiot',
  awaitingpayment: 'odotetaan maksua',
  orderdetails: 'Tilauksen tiedot',
  purchased: 'Ostettu',
  purchasepending: 'Ostos odottamassa',
  sent: 'Lähetetty',
  rewardearned: 'Ansaittu palkinto',
  rewardwithdrawn: 'Nostettu Palkinto',
  currency: 'Valuutta',
  yourpassphrase: 'salasanasi',
  nevershareseed: '* Älä koskaan jaa salasanaasi kenellekkään!',
  passphrasesaved: 'Olen tallentanut salasanani',
  willdolater: 'Teen tämän myöhemmin',
  checkwords:
    'Anna sanat varmistaaksesi, että olet kirjoittanut salasanan muistiin',
  goodtry: 'Hyvä yritys',
  cannotuseowncode: 'Et voi käyttää omaa referoinitkoodiasi',
  edit: 'Muokkaa',
  continue: 'Jatka joka tapauksessa',
  addressbig: 'Osoite',
  activate: 'Aktivoi',
  sharecodebutton: 'Jaa koodi',
  asell: 'Myy',
  // v1.3.2
  archived: 'Arkistoitu',
  fee: 'maksu',
  oneh: '1 tunti',
  halfh: '30 minuuttia',
  oneblock: '10 minuuttia',
  notenougfund: 'Ei tarpeeksi BTC:tä, yrita lähettää pienempi määrä',
  provideswift: 'Syötä BIC/SWIFT-koodi',
  swift: 'BIC/SWIFT',
  copied: 'kopioitu',
  sellsuccess: 'rahasi ovat matkalla',
  economy: 'talous',
  quotaError:
    'Olet saavuttanut päivärajan, peruuta joitain avoimia tilauksia tai odota 24 tuntia ',
  minsell: 'minimi määrä: 0.001 BTC',
  showcancelledtransactions: 'näytä peruuntuneet transaktiot',
};
