export default {
  welcomeToRelai: 'bienvenue chez Relai',
  sosimple: 'tellement simple',
  onboarding1_1: 'le moyen le plus simple',
  onboarding1_2: "d'investir en Bitcoin",
  onboarding2_1: 'pas de compte',
  onboarding2_2: "pas d'inscription",
  onboarding2_3: 'pas de dépôt bancaire',
  autoinvest: 'investissement automatique',
  onboarding3_1: 'investissement récurrent',
  onboarding3_2: 'investir à partir de CHF 10',
  agreeRelai: "Relai: j'accepte",
  agreeBity: "Bity: j'accepte",
  termsandconditions: 'les conditions juridiques',
  privacypolicy: 'la politique de confidentialité',
  and: 'et',
  startnow: 'commencer maintenant',
  restore_account: 'restaurer un compte',
  creatingbitcoinwallet: "création d'un portefeuille Bitcoin en cours",
  noinvestmentyet: "pas encore d'investissement",
  buybtc: 'acheter',
  sellbtc: 'vendre',
  tapbuybtcbutton: 'appuie sur le bouton acheter',
  tostartinvesting: 'pour commencer à investir',
  sendbtc: 'envoyer',
  receivebtc: 'recevoir',
  balance: 'total',
  unconfirmed: 'en attente de confirmation',
  taptheimage: "touche l'image pour",
  tobuyfirstbitcoin: 'acheter ton premier bitcoin',
  errorCreatingOrder:
    'erreur lors de la création de votre commande, réessayer plus tard',
  settings: 'réglages',
  profile: 'profil',
  rateus: 'évaluer cette application',
  followus: 'nous suivre',
  askforhelp: "demander de l'aide",
  security: 'sécurité',
  backupbtcwallet: 'sauvegarde du portefeuille Bitcoin',
  general: 'général',
  changelanguage: 'changer de langue',
  legal: 'légal',
  close: 'fermer',
  reachouttous: 'contacte-nous',
  btcbackup: 'sauvegarde du portefeuille',
  backuptextpre: "assure-toi d'écrire les",
  twelvewords: '12 mots',
  backuptextpost:
    'suivants et de les garder en sécurité afin de pouvoir restaurer ton portefeuille Bitcoin si jamais tu perds ton téléphone',
  savedmnemonic: "j'ai recopié les mots de la phrase mnémonique",
  btcaddress: 'adresse Bitcoin',
  copyaddress: "copier l'adresse",
  dismiss: 'rejeter',
  addresscopied: 'adresse Bitcoin copiée dans le presse-papiers',
  recipientbtcaddress: 'adresse Bitcoin du destinataire',
  entercorrectaddress: 'veuillez saisir une adresse Bitcoin correcte',
  next: 'suivant',
  back: 'retour',
  sendingbitcoin: 'envoi de Bitcoin',
  half: 'moitié',
  cancel: 'annuler',
  addsomebtc: 'ajouter des Bitcoins',
  maxbtcexceeded: 'montant maximum dépassé',
  youaresending: 'tu envoies',
  to: 'à',
  confirm: 'confirmer',
  amount: 'montant',
  date: 'date',
  confirmations: 'confirmations',
  blockheight: 'hauteur de bloc',
  details: 'détails',
  whichiban: 'depuis quel compte bancaire (IBAN) vas-tu investir?',
  entercorrectiban: 'saisir un IBAN correct',
  creatingorder: 'nous créons ta commande',
  iwanttobuy: 'je veux acheter du Bitcoin',
  iwanttosell: 'je veux vendre du Bitcoin',
  buy: 'acheter',
  minpurchase: 'achat minimum: {{currency}} {{min}}',
  sell: 'vendre',
  once: 'unique',
  weekly: 'hebdomadaire',
  monthly: 'mensuel',
  dontforgetref: "n'oublie pas la référence",
  usefollowingref: 'utilise la référence suivante lors de la commande : ',
  tobankaccount: 'sur le compte bancaire suivant',
  pay: 'payez',
  fromyouraccount: 'le paiement doit provenir de ton compte bancaire personnel',
  tapholdcopy:
    'appuie et maintiens le texte de ton choix pour copier dans le presse-papiers',
  recipient: 'bénéficiaire',
  reference: 'message de paiement',
  makesureuseref: "assure-toi d'utiliser la référence indiquée ci-dessus",
  mighttake3days:
    "cela peut prendre jusqu'à 3 jours pour recevoir tes bitcoins",
  done: 'terminé',
  illpaylater: 'je paierai plus tard',
  youriban: 'votre IBAN',
  inforequired:
    'le numéro du compte bancaire (IBAN) et le nom sont nécessaires pour le virement',
  somethingwrong: "une erreur s'est produite. merci d'essayer plus tard",
  entervalidiban: 'saisir un IBAN valide',
  paymentdetails: 'détails du paiement',
  amountsentto: 'le montant sera envoyé à',
  personalinfo: 'informations personnelles',
  fullname: 'nom complet',
  address: 'adresse',
  // provideaddress: 'indique ton nom complet',
  txoverview: 'aperçu de la transaction',
  youareselling: 'tu vends',
  inexchangeto: 'tu reçois',
  congrats: 'bravo!',
  investmentonitsway: 'ton investissement est en cours',
  sold: 'vendu',
  received: 'reçu',
  status: 'état',
  pending: 'en attente de ton paiement',
  refno: 'numéro de réference',
  orderid: 'numéro de commande',
  maxpurchase: 'achat maximum: {{currency}} {{max}}',
  keepappsecure: 'pour sécuriser ton application Relai',
  choosepin: 'choisir un code PIN',
  confirmpin: 'confirmer le code PIN',
  entriesnotmatch: 'les codes PIN ne correspondent pas',
  tryagain: 'réessayer',
  enterpin: 'entrer votre code PIN',
  incorrectpin: 'code PIN incorrect',
  alwayspin: "toujours besoin d'un code PIN",
  restore_btc: 'entre ta phrase mnémonique de 12 mots',
  restorebtcwarning:
    "nous vérifierons localement que ton adresse de portefeuille Bitcoin d'investissement correspond",
  agreetoterms:
    'tu dois accepter les conditions générales et la politique de confidentialité de Relai et Bity',
  restoringaccount: 'restauration du compte Relai',
  noaccountfound:
    "nous n'avons pas trouvé ton compte, vérifie tes informations et réessaie",
  provideibanwallet: 'fournir un numéro IBAN et une phrase mnémonique correcte',
  maxattempts: 'limite de tentatives atteinte',
  protectinfo:
    "pour protéger tes informations, l'accès à Relai a été verrouillé pendant 5 minutes",
  cancelorder: 'annuler la commande',
  cancellingorder:
    "tu es sur le point d'annuler ta commande. assure-toi d'annuler ton ordre de paiement auprès de ta banque s'il s'agit d'une commande récurrente",
  keeporder: "garder l'ordre",
  cancellingerror:
    "nous ne sommes pas en mesure d'annuler ta commande pour le moment. réessaie plus tard",
  investedsofar: "investi jusqu'à présent",
  succeeded: 'réussi',
  onlyhavetofillonce: "tu dois renseigner ce champ qu'une seule fois",
  invested: 'investi',
  changecurrency: 'changer la devise de référence',
  payto: 'payer à',
  taptochange: 'tape pour changer',
  delete: 'supprimer',
  toreceive: 'estimée',
  fees: 'nos frais',
  totalfee: 'frais totaux',
  relaifee: 'frais des services Relai',
  bityfee: 'frais de courtage Bity',
  onitsway: 'BTC en chemin',
  copyall: 'tout copier',
  payin48hours: 'il faut effectuer le paiement sous 48 heures',
  firstordertoohigh:
    'ton premier ordre doit être inférieur à {{max}} {{currency}}',
  fast: 'rapide',
  slow: 'lent',
  medium: 'moyen',
  referralcode: 'as-tu un code de référence?',
  codenotexisting: "ce code n'existe pas",
  provideaddress: 'quelle est ton adresse?',
  providefullname: 'quel est ton nom?',
  zip: 'code postal',
  providezip: 'quel est ton code postal',
  city: 'ville',
  providecity: 'quelle ville habites-tu?',
  country: 'pays',
  providecountry: 'dans quel pays vis-tu?',
  providereferralcode: 'ton code de référence',
  welcomereferral: 'bienvenue dans le programme de référence de Relai!',
  sharecode: 'partage ton code avec ton entourage',
  sharecode2: 'tu paies 0.5% de frais en moins (2.5% au lieu de 3%)',
  sharecode3chf:
    "tu recevras 0.5% pour chaque investissement utilisant ton code (par exemple 5 CHF pour 1'000 CHF investis)",
  sharecode3eur:
    "tu reçevras 0.5% pour chaque investissement utilisant ton code (par exemple 5 EUR pour 1'000 EUR investis)",
  sharecode4:
    'tu recevras tes gains chaque 15 du mois si le montant total est supérieur à 10',
  totalearnings: 'avoir total',
  noreferralearnings: 'pas de gain',
  startsharingcode: 'partage ton code de référence',
  toearnbtc: 'pour accumuler des bitcoins',
  generatecode: 'génère ton code en appuyant sur "activer"',
  hitherecode: 'Salut,\nvoici mon code de référence Relai: ',
  hitherecode2:
    "😎\nEn utilisant ce code tu paieras 0.5% de moins en frais!👍\nRelai est l'application la plus simple au monde pour investir dans le Bitcoin - made in Switzerland!🇨🇭\niOS: https://apps.apple.com/app/id1513185997\n Android: https://play.google.com/store/apps/details?id=com.relai",
  shareyourcode: 'partage ton code Relai',
  refcode: 'code de référence:',
  paymentinformation: 'information paiement',
  share: 'partager',
  pleasebackup: 'sauvegarde ton portefeuille BTC',
  pending2: 'en attente',
  transactions: 'transactions',
  awaitingpayment: 'en attente de paiement',
  orderdetails: "détails de l'ordre",
  purchased: 'acheté',
  purchasepending: 'achat en attente',
  sent: 'envoyé',
  rewardearned: 'gains',
  rewardwithdrawn: 'retrait des gains',
  currency: 'devises',
  yourpassphrase: 'votre passphrase',
  nevershareseed: '* ne jamais partager votre phrase mnémonique!',
  passphrasesaved: "j'ai noté les mots de la phrase mnémonique",
  willdolater: 'je prendrai note plus tard',
  checkwords: 'pour vérifier ta sauvegarde, saisis les mots',
  goodtry: 'bien essayé!',
  cannotuseowncode: 'tu ne peux pas utiliser ton propre code',
  edit: 'resaisir',
  continue: 'continuer',
  addressbig: 'addresse',
  activate: 'activer',
  sharecodebutton: 'partager code',
  asell: 'vente',
  // v1.3.2
  archived: 'archivé',
  fee: 'frais',
  oneh: '1 h',
  halfh: '30 min',
  oneblock: '10 min',
  notenougfund: 'pas assez de BTC!',
  provideswift: 'BIC/SWIFT',
  swift: 'BIC/SWIFT',
  copied: 'copié',
  sellsuccess: 'ton argent est en chemin',
  economy: 'économique',
  quotaError:
    'tu as atteint ton quota. Il faut annuler tes ordres impayés ou attendre 24h',
  minsell: 'somme minimum: 0.001 BTC',
  showcancelledtransactions: 'voir les ordres annulés',
  exchangerate: 'taux de change',
  insufficientfunds: 'pas assez de BTC, réessaie avec des frais moins élevés',
  // v1.4
  scanpaperwallet: 'scanner un portefeuille papier',
  custom: 'manuel',
  feetoolow: "l'envoi peut échouer si les frais sont trop faibles",
  stackedalot: 'tu as accumulé pas mal de BTC!',
  considerbitbox:
    'pense à améliorer ta sécurité avec un portefeuille matériel. Nous te conseillons BitBox02',
  whyhardwarewallet: 'pourquoi un portefeuille matériel?',
  whyhardwarewalletans:
    "Un porte-monnaie matériel est un dispositif spécialement conçu pour stocker tes bitcoins en toute sécurité. Tes fonds sont aussi en sécurité dans ton téléphone, mais les risques qu'il soit piraté, volé ou infecté par un logiciel malveillant sont beaucoup plus élevés que pour un dispositif matériel spécialisé. Si tu as plus de 500 euros en Bitcoin, nous te recommandons d'investir un peu d'argent pour améliorer ta sécurité.",
  checkitout: "plus d'info",
  maybelater: 'peut-être plus tard',
  why: 'pourquoi ?',
  letsgo: 'allons-y!',
  restoreexistingbackup: 'restaurer un portefeuille',
  onboarding_subtitle: 'la solution la plus simple pour le Bitcoin',
  onboarding_list_item_1: 'pas de compte',
  onboarding_list_item_2: 'automatise tes achats de Bitcoin',
  onboarding_list_item_3: 'montant minimum de 10 EURO/CHF',
  onboarding_list_item_4: 'tu gardes le contrôle de tes bitcoins',
  onboarding_step_title: 'comment ça marche',
  onboarding_step_index: 'étape {{index}} / 3',
  onboarding_step_1: "tu passes ton ordre sur l'application",
  onboarding_step_2: 'tu nous envoies un paiement bancaire',
  onboarding_step_3: "nous t'envoyons tes bitcoins",
  start: 'commencer',
  restore_account_subtitle: 'nous allons restaurer ton compte\nen 2 étapes',
  restore_account_step_1_description: 'saisis ton IBAN',
  restore_account_step_2_description: 'saisis ta phrase mnémonique de 12 mots',
  creatingbitcoinwallet: 'création du portefeuille',
  exceeds_quota:
    'tu as atteint ton quota. Il faut annuler tes ordres impayés ou attendre 24h',
  invalid_bank_account: 'IBAN incorrect, saisis un numéro IBAN valide',
  invalid_country_code: 'le code du pays est invalide',
  invalid_crypto_address: 'ton addresse BTC est invalide',
  invalid_bank_account_owner_address:
    'ton adresse est invalide, saisis-en une valide',
  malformed_request:
    "une erreur s'est produite, réessayer plus tard ou nous écrire un email à support@relai.ch",
  revolutiban:
    "Il n'est pas possible d'utiliser l'IBAN du compte collectif de Revolut",
  enablebiometrics: 'activer Touch ID / Face ID',
  ordercreated: 'your order has been initiated',
};
