export default {
  welcomeToRelai: 'benvenuti in Relai',
  sosimple: 'così semplice',
  onboarding1_1: 'il modo più semplice per',
  onboarding1_2: 'investire in bitcoin',
  onboarding2_1: 'nessun account',
  onboarding2_2: 'nessuna registrazione',
  onboarding2_3: 'nessun deposito',
  autoinvest: 'auto investimento',
  onboarding3_1: 'automatico e ricorrente',
  onboarding3_2: 'investimenti da 10 CHF',
  agreeRelai: "sono d'accordo con Relai",
  agreeBity: 'accetto Bity',
  termsandconditions: 'termini e condizioni',
  privacypolicy: 'politica di riservatezza',
  and: 'e',
  startnow: 'parti ora',
  restoreaccount: "ripristinare l'account",
  creatingbitcoinwallet: 'creare un portafoglio Bitcoin',
  noinvestmentyet: 'ancora nessun investimento',
  buybtc: 'acquista',
  sellbtc: 'vendi',
  tapbuybtcbutton: 'premi il pulsante Acquista BTC',
  tostartinvesting: 'inizia a investire',
  sendbtc: 'invia',
  receivebtc: 'ricevi',
  balance: 'saldo',
  unconfirmed: 'non confermato',
  taptheimage: "clicca l'immagine",
  tobuyfirstbitcoin: 'acquista il tuo primo Bitcoin',
  errorCreatingOrder:
    'errore durante la creazione del tuo ordine, riprova più tardi',
  settings: 'impostazioni',
  profile: 'profilo',
  rateus: 'valutaci',
  followus: 'seguici',
  askforhelp: 'chiedere aiuto',
  security: 'sicurezza',
  backupbtcwallet: 'backup portafoglio BTC',
  general: 'generale',
  changelanguage: 'cambia lingua',
  legal: 'legale',
  close: 'chiudi',
  followusonsocialmedia: 'seguici sui social media',
  reachouttous: 'contattateci',
  btcbackup: 'backup BTC',
  backuptextpre: 'assicurati di annotare le seguenti',
  twelvewords: '12 parole',
  backuptextpost:
    '(frase mnemonica) e tenerle al sicuro in modo da poter ripristinare i tuoi Bitcoin quando perdi il telefono',
  savedmnemonic: 'ho salvato la mia frase mnemonica',
  btcaddress: 'indirizzo BTC',
  copyaddress: 'copia indirizzo',
  dismiss: 'annulla',
  addresscopied: 'indirizzo BTC copiato negli appunti',
  recipientbtcaddress: 'indirizzo BTC del destinatario',
  entercorrectaddress: 'inserisci un indirizzo BTC corretto',
  next: 'avanti',
  back: 'indietro',
  sendingbitcoin: 'invio di Bitcoin',
  half: 'metà',
  cancel: 'annulla',
  addsomebtc: 'aggiungi un pó di BTC',
  maxbtcexceeded: 'BTC massimi superati',
  youaresending: 'stai inviando',
  to: 'verso',
  confirm: 'confermare',
  amount: 'quantità',
  date: 'data',
  confirmations: 'conferme',
  blockheight: 'altezza del blocco',
  details: 'dettagli',
  whichiban: 'da quale IBAN investirai?',
  entercorrectiban: 'inserisci un IBAN corretto',
  creatingorder: 'stiamo creando il tuo ordine',
  iwanttobuy: 'voglio comprare BTC',
  iwanttosell: 'voglio vendere BTC',
  buy: 'acquistare',
  minpurchase: 'acquisto minimo: {{min}} {{currency}}',
  sell: 'vendere',
  once: 'singolarmente',
  weekly: 'settimanalmente',
  monthly: 'mensilmente',
  dontforgetref: 'non dimenticare il codice di riferimento',
  usefollowingref:
    "utilizzare il seguente codice di riferimento quando si effettua l'ordine",
  tobankaccount: 'sul seguente conto bancario',
  pay: 'pagare',
  fromyouraccount: 'il pagamento deve provenire dal tuo conto bancario',
  tapholdcopy:
    'toccare e tenere premuto qualsiasi testo da copiare negli Appunti',
  recipient: 'destinatario',
  reference: 'messaggio di pagamento',
  makesureuseref: 'assicurarsi di utilizzare il riferimento sopra indicato',
  mighttake3days:
    'potrebbero essere necessari fino a 3 giorni per ricevere i tuoi Bitcoin',
  done: 'effettuato',
  illpaylater: 'pagherò più tardi',
  inforequired:
    'il tuo IBAN, nome e indirizzo sono necessari per il trasferimento dal conto bancario',
  somethingwrong: 'qualcosa è andato storto, per favore riprova più tardi',
  entervalidiban: 'inserisci un IBAN valido',
  paymentdetails: 'dettagli di pagamento',
  amountsentto: "l'importo verrà inviato a",
  personalinfo: 'informazioni personali',
  fullname: 'nome e cognome',
  address: 'indirizzo',
  // provideaddress: 'fornisci il tuo nome e cognome',
  txoverview: 'panoramica delle transazioni',
  youareselling: 'stai vendendo',
  inexchangeto: 'in cambio di',
  congrats: 'congratulazioni!',
  investmentonitsway: 'il tuo investimento sta arrivando',
  sold: 'venduto',
  received: 'ricevuto',
  status: 'stato',
  pending: 'in attesa del tuo pagamento',
  refno: 'numero di riferimento',
  orderid: 'ID ordine',
  maxpurchase: 'acquisto massimo: {{max}} {{currency}}',
  keepappsecure: 'per proteggere la tua app Relai',
  choosepin: 'scegli un codice PIN',
  confirmpin: 'conferma il tuo codice PIN',
  entriesnotmatch: 'il tuo PIN non corrisponde',
  tryagain: 'per favore riprova',
  enterpin: 'inserisci il tuo codice PIN',
  incorrectpin: 'codice PIN errato',
  alwayspin: 'richiedi sempre il codice PIN',
  restoreiban: 'con quale IBAN hai usato Relai?',
  restorebtc: 'inserisci la tua frase mnemonica di 12 parole',
  restorebtcwarning:
    "verificheremo solo localmente che l'indirizzo del tuo portafoglio BTC di investimento corrisponda",
  agreetoterms:
    "devi accettare i termini e condizioni di Relai e Bity e l'Informativa sulla privacy",
  restoringaccount: "ripristino dell'account Relai",
  noaccountfound:
    'impossibile trovare il tuo account, verifica le tue informazioni e riprova',
  provideibanwallet: 'fornisci il tuo IBAN e frase mnemonica corretti',
  maxattempts: 'numero massimo di tentativi raggiunti',
  protectinfo:
    "per proteggere le tue informazioni, l'accesso a Relai è stato bloccato per 5 minuti",
  cancelorder: 'annulla ordine',
  cancellingorder:
    "stai per annullare l'ordine, assicurati di interrompere il pagamento se si tratta di un ordine ricorrente",
  keeporder: 'tenere in ordine',
  cancellingerror:
    'al momento non siamo in grado di annullare il tuo ordine. Per favore riprova più tardi',
  investedsofar: 'hai investito finora',
  succeeded: 'eseguito',
  onlyhavetofillonce: 'da compilare solo una volta',
  invested: 'investito',
  changecurrency: 'cambia valuta corrente',
  payto: 'dettagli del pagamento',
  taptochange: 'premi per cambiare',
  delete: 'cancella',
  toreceive: 'stimato',
  fees: 'commissioni',
  totalfee: 'commissione totale',
  relaifee: 'commissione di servizio Relai',
  bityfee: 'commissione di mediazione Bity',
  onitsway: 'BTC sta arrivando',
  copyall: 'copia tutto',
  payin48hours:
    'per assicurare il corretto funzionamento del tuo pagamento, ti preghiamo di pagare entro 48 ore',
  firstordertoohigh:
    'il tuo primo pagamento dovrebbe essere <{{max}} {{currency}}',
  fast: 'veloce',
  slow: 'lento',
  medium: 'medio',

  referralcode: "Hai un codice d'affiliazione?",
  codenotexisting: "Il codice d'affiliazione inserito non esiste",
  provideaddress: 'Inserisci il tuo indirizzo',
  providefullname: 'Inserisci il tuo nome completo',
  zip: 'Codice postale',
  providezip: 'Inserisci il tuo codice postale',
  city: 'Città',
  providecity: 'Inserisci la tua città',
  country: 'Stato',
  providecountry: 'Inserisci il tuo Stato di appartenenza',
  providereferralcode: 'Inserisci il tuo codice di affiliazione',
  welcomereferral: 'Benvenuto nel programma di affiliazione di Relai!',
  sharecode: 'Condividi il tuo codice di affiliazione ad altre persone',
  sharecode2:
    'Loro pagheranno 0.5% in meno sulla commissione di Transazione (2.5% invece del 3%)',
  sharecode3chf:
    "Tu riceverai 0.5% su tutti i loro investimenti (per esempio 5 CHF ogni 1'000 CHF investiti)",
  sharecode3eur:
    "Tu riceverai 0.5% su tutti i loro investimenti (per esempio 5 EUR ogni 1'000 EUR investiti)",
  sharecode4:
    'Riceverai le tue ricompense sul tuo wallet  BTC ogni 15cesimo giorno del mese se hai accumulato più di 10',
  totalearnings: 'Ricompense totali',
  noreferralearnings: 'Nessuna ricompensa',
  startsharingcode: 'Inizia a condividere il tuo codice',
  toearnbtc: 'Guadagna BTC con il tuo codice affiliato',
  generatecode: 'Genera il tuo codice affiliato cliccando su "Attiva"',
  hitherecode: "Ciao, Questo è il mio codice d'affiliazione Relai: ",
  hitherecode2:
    '😎\nSe usi questo codice quando investi in Bitcoin con la Relai App, pagherai 0.5% in meno sulle commissioni! 👍\nRelai è il modo più facile al mondo per investire in Bitcoin - made in Switzerland! 🇨🇭\n iOS: https://apps.apple.com/app/id1513185997\n Android: https://play.google.com/store/apps/details?id=com.relai',
  shareyourcode: 'Condividi il tuo codice',
  refcode: 'Codice di Affiliazione:',
  paymentinformation: 'Informazioni di pagamento',
  share: 'Condividi',
  pleasebackup: 'Prego fare il backup del wallet',
  pending2: 'In attesa',
  transactions: 'Transazioni',
  awaitingpayment: 'In attesa del pagamento',
  orderdetails: 'Dettagli ordine',
  purchased: 'Acquistato',
  purchasepending: 'Acquisto in attesa',
  sent: 'Inviato',
  rewardearned: 'Ricompensa ricevuta',
  rewardwithdrawn: 'Ritira la ricompensa',
  currency: 'Valuta',
  yourpassphrase: 'La tua chiave segreta',
  nevershareseed: '* Non condividere la tua chiave segreta con nessuno!',
  passphrasesaved: 'Ho salvato la mia chiave segreta',
  willdolater: 'Lo farò più tardi',
  checkwords:
    'Per assicurare di aver scritto correttamente la tua chiave segreta, prego inserire le parole',
  goodtry: 'Buon tentativo',
  cannotuseowncode: 'Non puoi usare il tuo propio codice di affiliazione',
  edit: 'Modifica',
  continue: 'Continua comunque',
  addressbig: 'Indirizzo',
  activate: 'Attiva',
  sharecodebutton: 'Condividi il codice',
  asell: 'Vendita',
  // v1.3.2
  archived: 'Archiviata',
  fee: 'Commissioni',
  oneh: '1 ora',
  halfh: '30 min',
  oneblock: '10 min',
  notenougfund: 'Non hai abbastanza BTC!',
  provideswift: 'BIC/SWIFT',
  swift: 'BIC/SWIFT',
  copied: 'copiato',
  sellsuccess: 'il tuo capitale sta arrivando',
  economy: 'Economy',
  quotaError:
    'Hai raggiunto la tua quota massima, prego cancella alcuni ordini o aspetta 24 ore se hai già pagato i tuoi ordini',
  minsell: 'Importo minimo: 0.001 BTC',
  showcancelledtransactions: 'Visualizza le transazioni cancellate',
  exchangerate: 'Tasso di cambio',
  insufficientfunds:
    'Fondi insufficienti, prego prova con commissioni più basse.',
};
