export default {
  welcomeToRelai: 'welkom bij Relai',
  sosimple: 'zo eenvoudig',
  onboarding1_1: 'de makkelijkste manier om',
  onboarding1_2: 'bitcoin te sparen',
  onboarding2_1: 'geen account',
  onboarding2_2: 'geen registratie',
  onboarding2_3: 'geen storting',
  autoinvest: 'spaar automatisch',
  onboarding3_1: 'automatische, periodieke ',
  onboarding3_2: 'aankopen vanaf 10 EUR',
  agreeRelai: 'Ik ga akkoord met Relai's',
  agreeBity: 'Ik ga akkoord met Bity's',
  termsandconditions: 'voorwaarden',
  privacypolicy: 'privacybeleid',
  and: 'en',
  startnow: 'begin nu',
  restoreaccount: 'portemonnee herstellen',
  creatingbitcoinwallet: 'Bitcoin portemonnee aanmaken...',
  noinvestmentyet: 'nog geen aankopen',
  buybtc: 'koop',
  sellbtc: 'verkoop',
  tapbuybtcbutton: 'druk op koop',
  tostartinvesting: 'om BTC te sparen',
  sendbtc: 'verstuur',
  receivebtc: 'ontvang',
  balance: 'saldo',
  unconfirmed: 'onbevestigd',
  taptheimage: 'druk op de afbeelding',
  tobuyfirstbitcoin: 'om jouw eerste bitcoin te kopen',
  errorCreatingOrder:
    'er liep iets mis, probeer het later opnieuw',
  settings: 'instellingen',
  profile: 'profiel',
  rateus: 'beoordeel ons',
  followus: 'volg ons',
  askforhelp: 'contacteer ons',
  security: 'veiligheid',
  backupbtcwallet: 'back-up BTC portemonnee',
  general: 'algemeen',
  changelanguage: 'kies taal',
  legal: 'legaal',
  close: 'sluiten',
  followusonsocialmedia: 'volg ons',
  reachouttous: 'contacteer ons',
  btcbackup: 'BTC back-up',
  backuptext:
    'schrijf onderstaande 12 woorden (seed) neer op papier en bewaar ze veilig zodat je jouw portemonnee kan herstellen mocht je jouw toestel verliezen',
  savedmnemonic: 'ik heb mijn 12 woorden genoteerd',
  btcaddress: 'BTC adres',
  copyaddress: 'kopieer BTC adres',
  dismiss: 'afwijzen',
  addresscopied: 'BTC adres gekopieerd naar klembord',
  recipientbtcaddress: 'BTC adres van ontvanger',
  entercorrectaddress: 'gelieve een correct BTC adres op te geven',
  next: 'volgende',
  back: 'terug',
  sendingbitcoin: 'Bitcoin versturen',
  half: 'half',
  cancel: 'annuleer',
  addsomebtc: 'voeg wat BTC toe',
  maxbtcexceeded: 'max BTC overschreden',
  youaresending: 'je verstuurt',
  to: 'naar',
  confirm: 'bevestig',
  amount: 'bedrag',
  date: 'datum',
  confirmations: 'confirmaties',
  blockheight: 'blokhoogte',
  details: 'details',
  whichiban: 'vanaf welke IBAN zal je investeren?',
  entercorrectiban: 'gelieve een correcte IBAN in te geven',
  creatingorder: 'we finaliseren dit order',
  iwanttobuy: 'Ik wil BTC kopen',
  iwanttosell: 'Ik wil BTC verkopen',
  buy: 'koop',
  minpurchase: 'minimum bedrag: 10 EUR',
  sell: 'verkoop',
  once: 'eenmalig',
  weekly: 'wekelijks',
  monthly: 'maandelijks',
  dontforgetref: "vergeet de referentie niet toe te voegen",
  usefollowingref:
    'gebruik de volgende mededeling wanneer je overschrijft \n\n',
  tobankaccount: 'naar deze bankrekening',
  pay: 'betaal',
  fromyouraccount: 'de betaling moet van jouw eigen bankrekening komen',
  tapholdcopy: 'tik en houd vast om de tekst te kopieren',
  recipient: 'ontvanger',
  reference: 'mededeling bij betaling',
  makesureuseref: 'voeg bij betaling bovenstaande mededeling toe',
  mighttake3days: 'Het kan tot 3 dagen duren om jouw Bitcoin te ontvangen',
  done: 'klaar',
  illpaylater: "Ik betaal later",
  inforequired:
    'IBAN, naam en adres informatie is vereist voor de bankoverschrijving',
  somethingwrong: 'er liep iets mis, probeer het later opnieuw',
  entervalidiban: 'gelieve een geldig IBAN in te geven',
  paymentdetails: 'details betaling',
  amountsentto: 'het bedrag zal verstuurd worden naar',
  personalinfo: 'persoonlijke informatie',
  fullname: 'Volledige naam',
  address: 'adres',
  // provideaddress: 'Geef voledige naam',
  txoverview: 'overzicht transactie',
  youareselling: 'je verkoopt',
  inexchangeto: 'in ruil voor',
  congrats: 'gefeliciteerd!',
  investmentonitsway: 'Jouw aankoop is onderweg',
  sold: 'verkocht',
  received: 'ontvangen',
  status: 'status',
  pending: 'in afwachting van betaling',
  refno: 'mededeling ter referentie',
  orderid: 'order ID',
  maxpurchase: 'max bedrag: 5000 EUR',
  keepappsecure: 'om de Relai app te beveiligen',
  choosepin: 'kies een PIN code',
  confirmpin: 'bevestig de PIN code',
  entriesnotmatch: 'PIN kwam niet overeen',
  tryagain: 'probeer opnieuw aub',
  enterpin: 'geef PIN code',
  incorrectpin: 'verkeerde PIN code',
  alwayspin: 'toegangscode inschakelen',
  restoreiban: 'welke IBAN gebruikte je voor Relai',
  restorebtc: 'geef wachtwoordzin van 12 woorden (seed) op',
  restorebtcwarning:
    'we zullen enkel lokaal controleren dat jouw BTC adres overeenkomt met jouw portemonnee',
  agreetoterms:
    'je moet akkoord gaan met de voorwaarden en privacybeleid van Relai en Bity',
  restoringaccount: 'Relai portemonnee herstellen...',
  noaccountfound:
    "We konden jouw rekening niet vinden, controleer de gegevens en probeer opnieuw",
  provideibanwallet: 'geef een correcte IBAN en seed op aub',
  maxattempts: 'maximale pogingen overschreden',
  protectinfo:
    'om jouw gegevens te beschermen, is toegang tot Relai geblokkeerd voor 5 minuten.',
  cancelorder: 'annuleer order',
  cancellingorder:
    'je staat op het punt om jouw order te annuleren \n\n zorg ervoor dat je de betaling stopzet als dit een terugkerende bestelling is',
  keeporder: 'behoud order',
  cancellingerror:
    'we kunnen jouw order momenteel niet annuleren. probeer het later opnieuw',
  investedsofar: 'reeds gespaard',
  succeeded: 'geslaagd',
  onlyhavetofillonce: 'je hoeft dit maar één keer in te vullen',
  invested: 'gespaard',
  changecurrency: 'valuta aanpassen',
  payto: 'details van betaling',
  taptochange: 'tik om te wijzigen',
  delete: 'verwijder',
  toreceive: 'geschat',
  fees: 'onze kosten',
  totalfee: 'totale kosten',
  relaifee: 'Relai servicekosten',
  bityfee: 'Bity makelaarskosten',
  onitsway: 'BTC is onderweg',
  copyall: 'kopieer alles',
  payin48hours:
    'betaal binnen 48 uur om een correcte afhandeling van jouw betaling te garanderen',
  firstordertoohigh: 'Jouw eerste bestelling moet <100 EUR zijn',
  fast: 'snel',
  slow: 'traag',
  medium: 'gemiddeld',

  // v1.3
  referralcode: 'heb je een verwijzingscode?',
  codenotexisting: "De door jou ingevoerde verwijzingscode bestaat niet",
  provideaddress: 'Geef adres op',
  providefullname: 'Geef volledige naam op',
  zip: 'Postcode',
  providezip: 'Geef Postcode op',
  city: 'Stad',
  providecity: 'Geef Stad op',
  country: 'Land',
  providecountry: 'Kies Land',
  providereferralcode: 'Geef verwijzingscode op',
  welcomereferral: 'Welkom bij het verwijzingsprogramma van Relai!',
  sharecode: 'Deel verwijzingscode met andere mensen',
  sharecode2:
    'Ze betalen 0,5% minder transactiekosten (2,5% in plaats van 3%)',
  sharecode3chf:
    "Je verdient 0,5% op al hun aankopen (bijv. 5 CHF per 1.000 geïnvesteerde CHF)",
  sharecode3eur:
    "Je verdient 0,5% op al hun aankopen (bijv. 5 EUR per 1.000 geïnvesteerde EUR)",
  sharecode4:
    'Je ontvangt jouw beloningen elke 15e van de maand in jouw BTC-portemonnee als je er meer dan 10 hebt verzameld',
  totalearnings: 'Totale winst',
  noreferralearnings: 'Geen verwijzingsinkomsten',
  startsharingcode: 'Begin met het delen van jouw code',
  toearnbtc: 'om BTC te verdienen met jouw verwijzingscode',
  generatecode: 'Genereer jouw verwijzingscode door op "Activeren" te klikken',
  hitherecode: 'Hallo daar,\nHier is mijn Relai verwijzingscode: ',
  hitherecode2:
    '😎\nAls je het gebruikt om Bitcoin te sparen met de Relai App, betaal je 0,5% minder aan kosten! 👍\nRelai is 's werelds gemakkelijkste manier om in Bitcoin te sparen - gemaakt in Zwitserland! 🇨🇭\niOS: https://apps.apple.com/app/id1513185997\nAndroid: https://play.google.com/store/apps/details?id=com.relai',
  shareyourcode: 'Deel Relai-verwijzingscode',
  refcode: 'Verwijzingscode:',
  paymentinformation: 'Betalingsinformatie',
  share: 'deel',
  pleasebackup: 'maak een back-up van jouw portemonnee',
  pending2: 'In afwachting',
  transactions: 'Transacties',
  awaitingpayment: 'in afwachting van betaling',
  orderdetails: 'Details van order',
  purchased: 'Gekocht',
  purchasepending: 'Aankoop in behandeling',
  sent: 'Verstuurd',
  rewardearned: 'Beloning verdiend',
  rewardwithdrawn: 'Beloning afgehaald',
  currency: 'Valuta',
  yourpassphrase: 'jouw watchwoordzin (seed)',
  nevershareseed: '* Deel deze wachtwoordzin met niemand!',
  passphrasesaved: 'Ik heb mijn wachtwoordzin opgeslagen',
  willdolater: 'ik doe het later',
  checkwords:
    'Geef woorden op om zeker te zijn dat je de wachtwoordzin hebt opgeschreven',
  goodtry: 'Goeie poging',
  cannotuseowncode: 'Je kan je eigen verwijzingscode niet gebruiken',
  edit: 'Bewerk',
  continue: 'Ga toch verder',
  addressbig: 'Adres',
  activate: 'Activeren',
  sharecodebutton: 'Deel code',
  asell: 'Verkoop',
  // v1.3.2
  archived: 'Gearchiveerd',
  fee: 'vergoeding',
  oneh: '1 uur',
  halfh: '30 min',
  oneblock: '10 min',
  notenougfund: 'Niet genoeg BTC, probeer een kleiner bedrag te sturen!',
  provideswift: 'Geef BIC / SWIFT op',
  swift: 'BIC/SWIFT',
  copied: 'gekopieerd',
  sellsuccess: 'jouw geld is onderweg',
  economy: 'economie',
};
